Bug/gh761 switch domain shows selected domain
RHEAGROUP/COMET-IME-Community-Edition pull request #1050
Opened 2022-05-02 08:05 UTC by omaratrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Switch domain dialog shows currently selected domain instead of the default domain.

2022-05-02 08:08 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/ModelIterationDomainSwitchDialogViewModel.cs
> +                    modelrow.ActiveParticipant.SelectedDomain = modelrow.SelectedDomain;
Why do you need this? The switching should already have happened and the dialog is presumably closing.

2022-05-02 08:09 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/ModelSelectionIterationSetupRowViewModel.cs
> +                var selectedDomain2 = this.ActiveParticipant.SelectedDomain.Name;
Why do you need this? Not being used anywhere...

2022-05-02 08:10 UTC, samatrhea requested changes

2022-05-02 08:10 UTC, samatrhea commented on CDP4ShellDialogs/ViewModels/ModelSelectionIterationSetupRowViewModel.cs
> +                var selectedDomain2 = this.ActiveParticipant.SelectedDomain.Name;
I have the impression that `selectedDomain2` is set but never used, if that is indeed the case, please remove

2022-05-02 08:10 UTC, samatrhea commented on CDP4ShellDialogs/ViewModels/ModelSelectionIterationSetupRowViewModel.cs
> +                this.SelectedDomain = this.DomainOfExpertises.Contains(this.ActiveParticipant.SelectedDomain)
not sure why this code is changed, this is not related to the ticket?

2022-05-03 08:34 UTC, alexatrhea requested changes
Please pay attention to correct naming and documentation.

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/ModelIterationDomainSwitchDialogViewModel.cs
>          /// Gets the Select <see cref="ICommand"/>
Correct the documentation pls.

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/ModelIterationDomainSwitchDialogViewModel.cs
>          /// Gets the list of <see cref="BaseRowViewModel"/> available
Correct documentation.

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainEngineeringModelSetupRowViewModel.cs
> +// <copyright file="ModelSelectionEngineeringModelSetupRowViewModel.cs" company="RHEA System S.A.">
incorrect name

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainEngineeringModelSetupRowViewModel.cs
> +// <copyright file="ModelSelectionEngineeringModelSetupRowViewModel.cs" company="RHEA System S.A.">
Please regenerate the headers on all of the new files.

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainEngineeringModelSetupRowViewModel.cs
> +        /// Gets the <see cref="IterationSetupRowViewModel"/> that are contained by the row-view-model
Use correct class name in doc.

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainEngineeringModelSetupRowViewModel.cs
> +        private void InitializeContainers()
Rename method to `InitializeContainedRows` and update the documentation.

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainEngineeringModelSetupRowViewModel.cs
> +        /// Add the <see cref="IterationSetup"/> to the contained <see cref="IterationSetupRowViewModels"/>
Use correct class name for the row.

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainEngineeringModelSetupRowViewModel.cs
> +        private void AddIteration(IterationSetup iteration)
variable should be `iterationSetup` and update name in doc.

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainIterationSetupRowViewModel.cs
> +﻿// --------------------------------------------------------------------------------------------------------------------
new header needed.

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainIterationSetupRowViewModel.cs
> +        /// Initializes a new instance of the <see cref="ModelIterationDomainSwitchDialogViewModel"/> class.
Update class name

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainSessionRowViewModel.cs
> +﻿// --------------------------------------------------------------------------------------------------------------------
New header

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainSessionRowViewModel.cs
> +    /// The purpose of the <see cref="SessionRowViewModel"/> is to represent a <see cref="Session"/> and its <see cref="SiteDirectory"/>
Use correct class name.

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainSessionRowViewModel.cs
> +        /// Initializes a new instance of the <see cref="ModelSelectionSessionRowViewModel"/> class.
Correct class name

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainSessionRowViewModel.cs
> +        /// Gets the <see cref="EngineeringModelSetupRowViewModel"/> that are contained by the row-view-model
Use correct class name

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainSessionRowViewModel.cs
> +        private void AddModelRowViewModel(EngineeringModelSetup model)
parameter should be `engineeringModelSetup` and update the docs.

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogsTestFixture/ViewModels/ModelIterationDomainSwitchDialogViewModelTestFixture.cs
> +﻿// --------------------------------------------------------------------------------------------------------------------
Headers should be correct.

2022-05-03 08:34 UTC, alexatrhea commented on CDP4ShellDialogsTestFixture/ViewModels/SwitchDomainSessionTextFixture.cs
> +// <copyright file="ModelSelectionSessionTestFixture.cs" company="RHEA System S.A.">
Header

2022-05-03 12:58 UTC, alexatrhea requested changes

2022-05-03 12:58 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/ModelIterationDomainSwitchDialogViewModel.cs
>          /// Gets the Select <see cref="ICommand"/>
This is not resolved. should be "Gets the Switch <see cref=" not Select

2022-05-03 12:58 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainEngineeringModelSetupRowViewModel.cs
> +        /// Add the <see cref="IterationSetup"/> to the contained <see cref="IterationSetupRowViewModels"/>
this is not resolved

2022-05-03 12:58 UTC, alexatrhea commented on CDP4ShellDialogs/ViewModels/SwitchDomainEngineeringModelSetupRowViewModel.cs
> +        private void AddIteration(IterationSetup iteration)
not resolved

2022-05-03 13:41 UTC, alexatrhea approved these changes

2022-05-04 11:34 UTC, merged