Show/Hide deprecated domains in active model dialog
RHEAGROUP/COMET-IME-Community-Edition pull request #1059
Opened 2022-05-11 13:02 UTC by omaratrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Show/Hide deprecated domains when editing an engineering model

2022-05-11 13:10 UTC, alexatrhea requested changes

2022-05-11 13:10 UTC, alexatrhea commented on CDP4Composition/CommonView/ViewModels/Rows/ActiveDomainRowViewModel.cs
> +    public class ActiveDomainRowViewModel : ReactiveObject
docs missing

2022-05-11 13:10 UTC, alexatrhea commented on CDP4Composition/CommonView/ViewModels/Rows/ActiveDomainRowViewModel.cs
> +﻿// --------------------------------------------------------------------------------------------------------------------
Add a unit test for this new row

2022-05-11 13:10 UTC, alexatrhea commented on EngineeringModel/ViewModels/Dialogs/EngineeringModelSetupDialogViewModel.cs
> +﻿// --------------------------------------------------------------------------------------------------------------------
Please create/update the unittests to test all the new changes, since this is pretty drastic.

2022-05-11 13:10 UTC, alexatrhea commented on EngineeringModel/ViewModels/Dialogs/EngineeringModelSetupDialogViewModel.cs
> -        #region Properties
Please remove all # regions in this file, we don't use them anymore.

2022-05-11 13:10 UTC, alexatrhea commented on EngineeringModel/Views/Dialogs/EngineeringModelSetupDialog.xaml
> +        <FontStyleConverter x:Key="FontStyleConverter"></FontStyleConverter>
is this one still needed?

2022-05-12 05:34 UTC, samatrhea approved these changes

2022-05-12 08:28 UTC, lxatrhea approved these changes

2022-05-12 08:39 UTC, merged