[FIX] Requirements verification causes exception if no top element is set
RHEAGROUP/COMET-IME-Community-Edition pull request #1156
Opened 2022-09-02 13:53 UTC by jan-at-rhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Now a message box with error description will be displayed and verification will be aborted.

2022-09-02 13:54 UTC, jan-at-rhea commented on CDP4Composition/Services/DownloadFileService/DownloadFileService.cs
> +        /// The <see cref="IMessageBoxService"/> used to show user messages.
This is a fix, DevExpress isn't used here.

2022-09-02 14:46 UTC, samatrhea requested changes
code looks very good, nice and clean. Some small requests to change the feedback to the user (message and severity of icon)

2022-09-02 14:46 UTC, samatrhea commented on Requirements/ViewModels/RequirementBrowser/RequirementsBrowserViewModel.cs
> +                        this.messageBoxService.Show("Requirements can't be verified.\nTop Element is not set.", "Verification failed", MessageBoxButton.OK, MessageBoxImage.Error);
i propose we change 
  - the message to: Verification not performed.
  - the icon from error to something more friendly like warning or information

2022-09-05 06:45 UTC, samatrhea approved these changes

2022-09-05 07:04 UTC, lxatrhea approved these changes

2022-09-05 07:21 UTC, merged