Deleting possible finite states shows a warning message box #36
RHEAGROUP/COMET-IME-Community-Edition pull request #1160
Opened 2022-09-08 14:16 UTC by jaimeatrhea

### Prerequisites

- [ ] I have written a descriptive pull-request title
- [ ] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/pulls) open
- [ ] I have verified that I am following the COMET-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description

When deleting possible finite state list or a possible finite state the user will see a message box to warn the user about the implications of that deletion. 
Associated to the Task #36.

2022-09-09 14:04 UTC, samatrhea approved these changes

2022-09-12 09:26 UTC, lxatrhea requested changes
I think the issue needs a little bit more: Showing the amount of parameters that use the Possible Finita States.

2022-09-19 07:10 UTC, lxatrhea approved these changes

2022-09-19 07:13 UTC, samatrhea approved these changes

2022-09-21 07:05 UTC, merged