Feat/Grapher shows placeholder when no Top Element; fix#1260
RHEAGROUP/COMET-IME-Community-Edition pull request #1261
Opened 2023-06-16 07:16 UTC by jaimeatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Two properties to control the Grapher visibility and the placeholder visibility are added.

2023-06-16 10:13 UTC, samatrhea requested changes

2023-06-16 10:13 UTC, samatrhea commented on CDP4Grapher/Views/Grapher.xaml
> +                            The current Iteration for this option does not contain a Top Element
let s rephrase to:

"The Graph cannot be rendered as the Iteration does not contain a Top Element"

2023-07-01 12:53 UTC, nathanatrhea approved these changes

2023-07-04 06:59 UTC, samatrhea approved these changes

2023-07-04 07:05 UTC, merged