[Add] Support for CommonFileStore
RHEAGROUP/COMET-IME-Community-Edition pull request #1293
Opened 2023-11-01 14:23 UTC by lxatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
[Add] Support for CommonFileStore

2023-11-01 14:32 UTC, samatrhea requested changes
minor changes requested on file headers, code looks good, no need to pass by again

2023-11-01 14:32 UTC, samatrhea commented on CDP4Composition/Mvvm/MenuItems/RibbonButtonEngineeringModelDependentViewModel.cs
> +//    Copyright (c) 2015-2020 RHEA System S.A.
2023

2023-11-01 14:32 UTC, samatrhea commented on CDP4Composition/Mvvm/MenuItems/SessionEngineeringModelMenuGroupViewModel.cs
> +//   Copyright (c) 2017 RHEA System S.A.
please use correct header

2023-11-01 14:32 UTC, samatrhea commented on EngineeringModel/ViewModels/Dialogs/CommonFileStoreDialogViewModel.cs
> +//    Copyright (c) 2015-2020 RHEA System S.A.
2023

2023-11-06 10:34 UTC, jaimeatrhea approved these changes

2023-11-06 13:47 UTC, merged