feat: #GH73 make DoE and participant shown as subnodes
RHEAGROUP/COMET-IME-Community-Edition pull request #910
Opened 2021-08-02 12:14 UTC by SimonWoodRhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Engineering model layout changes.
Participants now show DoE as child nodes
DoE rows also show participants as child nodes. Edit and depreciate menu options have been removed.

2021-08-02 12:42 UTC, alexatrhea requested changes
very small things noticed.

2021-08-02 12:42 UTC, alexatrhea commented on CDP4SiteDirectory/ViewModels/ModelBrowser/Rows/ModelParticipantRowViewModel.cs
> +            if (showDomains)
`this.` qualifier missing

2021-08-02 12:42 UTC, alexatrhea commented on CDP4SiteDirectory/ViewModels/ModelBrowser/Rows/EngineeringModelSetupRowViewModel.cs
> +            UpdateDomainParticipants(this.Thing.Participant);
`this.` qualifier missing

2021-08-02 12:47 UTC, lxatrhea approved these changes

2021-08-02 15:02 UTC, alexatrhea approved these changes

2021-08-02 15:08 UTC, merged

2021-10-06 16:24 UTC, MartinFijneman commented
this issue was tested for 9.0.0 RC1, working as expected, with the exception of updating as reported in separate issue #932